version: "3.3"
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "8080:8080"
      - "443:443"   # HTTPS port
    container_name: rtmp_server
    volumes:
      - ./data:/tmp/hls
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/ssl:ro  

  auth:
    build: ./auth
    container_name: auth_server
